# Generated by Django 4.0.4 on 2022-04-12 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_coment', models.CharField(max_length=150)),
                ('email_coment', models.EmailField(max_length=254)),
                ('comentario', models.TextField(max_length=500)),
                ('data_coment', models.DateTimeField(default=django.utils.timezone.now)),
                ('publicado_coment', models.BooleanField(default=False)),
                ('post_coment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('user_coment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
